name: profile_page_app
description: A new Flutter project for a profile page with image picker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4

flutter:
  uses-material-design: true
